import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <p className="text-center">Model viewer in next js</p>
        {children}
      </body>
    </html>
  );
}
